runtime: python39
entrypoint: gunicorn -b :$PORT validateapp.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "validateapp.settings"
  # GOOGLE_APPLICATION_CREDENTIALS: 'unused'
automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
